# Generated by Django 3.2.7 on 2021-09-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='description_Lieu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ville',
            name='description_ville',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ville',
            name='image_ville',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='latitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='longitude',
            field=models.CharField(max_length=50),
        ),
    ]
